### ISSUE TITLE
Write Script Missing

### ISSUE THREAD

**Issue by norm21499** [axc450/pbs#19] opened 2022-11-25 04:42 UTC
The ability to write scripts is missing when right-clicking on an existing saved team.
![image](https://user-images.githubusercontent.com/119028014/203902769-77bc730e-ff69-4603-b0a9-c40b1096b432.png)

**Comment by GurliGebis** [comment] 2022-11-25 06:55
I had the same issue, seemed like for some reason, the addon files where missing from my Addons folder. (bug in my addon manager when switching from the old addon to the new one)
Can you confirm the tdBattlrPetScripts folder is in there, with files in it? 🙂

**Comment by norm21499** [comment] 2022-11-25 18:55
Looks like I do have a tdBattlePetScript folder with files in it. Looks like each subfolder also contains files. Something very specific is probably missing?

![image](https://user-images.githubusercontent.com/119028014/204041825-7b5639ea-0a6a-427b-8063-3dc4537dc635.png)

**Comment by GurliGebis** [comment] 2022-11-25 19:21
Looks correct to me.

**Comment by naofabo** [comment] 2022-12-04 12:30
hi. I got the same problem. is there a known solution for that? :)

**Comment by norm21499** [comment] 2022-12-04 15:13
I was able to fix my issue, but it was with trial and error. I disabled all of my addons. I re-enabled only Recount and logged in. Logged out and then re-enabled Pet Battle Scripts. that seemed to fix the issue for me, but I can't be sure if this would work for you as well if you haven't already tried it.

**Comment by eTzmNcbkrng** [comment] 2023-01-04 14:02
In your screenshot it shows Windows Explorer as recognising the file as a .TOC but it also shows the file being named `tdBattlePetScript.TOC`, as in, the extension is showing but not for any other files.

Can you rename it to just `tdbattlePetScript` and see if that fixes anything, if you enable File Extensions it might become more obvious what the problem is.
![image](https://user-images.githubusercontent.com/26512802/210571700-731cbd52-aacc-4a48-ad39-272a727d115e.png)

**Comment by bloerwald** [comment] 2023-01-10 22:24
Hi everyone having this issue.

As dumb as it sounds, but this issue is usually one of these:
- the add-on just isn't installed. 
- the add-on is installed, but is disabled in the interface settings.
- the old add-on is installed
- the new add-on is installed, but the installation is broken.

If you're having this issue, I strongly suggest the following steps:

- go to `…wow/Interface/Addons`, and delete the folders `tdBattlePetScript` and `tdBattlePetScript_Rematch`. 
- restart your add-on management software so it picks up that the add-on was forcibly removed. If it didn't pick that up, remove it again in there.
- Install the new add-on.
- You should now have `…wow/Interface/Addons/tdBattlePetScript` again. It should contain a folder `Rematch`. If it does not contain the `Rematch` folder, you installed the wrong add-on.
- Start the game. On the login screen verify that the add-on shows up in the add-on list **and is enabled**. Alternatively check that in-game, the menu should be the same.

By verifying the `Rematch` folder is there, you made sure the right add-on is installed. By checking the list you made sure the add-on is enabled (this is a common issue since users disabled the *broken* add-on and this add-on tries to impersonate the broken one, thus can be disabled even if freshly installed!). 

The button should now be available again. If it isn't, please complain on this ticket again.

**Comment by bloerwald** [comment] 2023-10-26 21:15
The transition period seems to be over. Closing this ticket to clean up

**Closed by bloerwald** 2023-10-26 21:15 UTC
Labels: bug
